### ISSUE TITLE
Bug??

### ISSUE THREAD

**Issue by gamegam** [NopeNotDark/Sniper#1]
When you damage an entity with the sniper, it also damages people behind walls.

**Comment by NopeNotDark** [comment]
I forgot to take that in to account lol, thanks for submitting this

**Comment by NopeNotDark** [comment]
Fixed in latest update [commit](https://github.com/NopeNotDark/Sniper/commit/d7a2fdb8c092a4f67da87ea12568f85c61a18162)
Make sure to erase past plugin_data data.
