### ISSUE TITLE
Error? #2

### ISSUE THREAD

**Issue by gamegam** [NopeNotDark/Sniper#2]
It does, but no damage.

I kept hitting him with a gun, but he didn't take any damage.

**Comment by NopeNotDark** [comment]
I'll look into this, only tested with entity's such as zombies, did you also update the config?

**Comment by gamegam** [comment]
Downloaded and edited. Config is like the latest update.

**Comment by gamegam** [comment]
yes no Attacks also damage entities behind walls.

**Comment by NopeNotDark** [comment]
Alright, i'll look into this, thanks for submitting this issue

**Comment by NopeNotDark** [comment]
Error should be fixed now, let me know if you find and more errors
