### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by aleksbrin** [NopeNotDark/Sniper#4]
Error: Implicit conversion from float 593.6922 to int loses precision
File: pmsrc/src/world/World
Line: 1774
Type: ErrorException

**Comment by NopeNotDark** [comment]
Which version are you using?

**Comment by aleksbrin** [comment]
2.0.2-alpha and 5.0 pmmp

**Comment by NopeNotDark** [comment]
Try latest 2.0.4-ALPHA
